### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by Friedd** [cogdog/wp-dimension#9] opened 2021-09-28 11:04 UTC
Hi there, 
since the last WP update my website goes black.
Looks like a problem with "body-is.loading"

try to hit bruitdavril.fr and reload the page if it appears (reloading makes it black). 
any idea ?

thanks.
Fred

**Comment by cogdog** [comment] 2021-09-28 19:12
Hi Fred,

Thanks for using this theme, which looks great on your site. I cannot reproduce this error on Chrome (OSX) but did see it on Firefox (a shift reload took care of it).  The same for my own site https://cog.dog 

I have found posts describing this same error I found in the console:
https://bugzilla.mozilla.org/show_bug.cgi?id=1643186

I will see what I can discover... I might need to look at the HTMLUP theme this is built on

**Comment by Friedd** [comment] 2021-09-28 22:39
Hi Alan, 
Thanks for your answer.

i've got this error on safari and chrome (both osx and ios) i only use these 2.
In both case the first load is ok, but if you navigate through the menu and then reload or leave and come back the site blocks on black.
Your site has the same problem on chrome but runs perfectly fine on safari, I'm not an expert but maybe that's a first clue.

If i can help let me know.

**Comment by cogdog** [comment] 2021-09-30 14:31
I'm not too deeply skilled on browser specific issues... I do think it might be an issue with the original HTML5Up template I used to build this from, the newer version seems to be using different Javascript libraries, so I am hoping if I can change everything out (reformatting all the WordPress templates) it might fix the issue?

**Comment by cogdog** [comment] 2021-10-03 00:28
I made updates (and pushed changes here) to make it use newer styles and scripts in the HTML5Up Dimension template. It might need more testing, but this newer version is running now at https;//cog.dog

**Comment by Friedd** [comment] 2021-10-04 15:49
Hi Alan, 
cog.dog looks good on safari & chrome osx on my side.
i'll update mine and see, i'm sure it'll be ok.

**Comment by Friedd** [comment] 2021-10-04 15:55
And it works yay !
thanks a lot Alan, I really appreciate !

**Comment by cogdog** [comment] 2021-10-04 17:33
That's great news, Fred. It was a good prompt for me to update the theme, thanks. Let me know if there are any CSS issues, I am not too sure how much changed under the hood. I am closing this issue, but feel free to open a new one.

Alan

**Closed as completed by cogdog** 2021-10-04 17:33 UTC
